# Note this test was performed using PY2; recent versions of PY3 will allow you to import the
# package even though no __init__.py exists (i.e. PY3 >= 3.3 will allow packages without 
# __init__.py files in certain contexts).

$ python

>>> import mytest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named mytest

>>> import mytest.world
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named mytest.world

>>> import mytest.simple
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named mytest.simple

